services:
  sample-app:
    image: asia-south1-docker.pkg.dev/gke-arena/asif-repo/sample-app:${BUILD_NUMBER}
    container_name: sample-app
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=production
      - BUILD_NUMBER=${BUILD_NUMBER:-1}
    restart: unless-stopped
